# Generated by Django 3.2.12 on 2024-02-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
