# Generated by Django 3.2.12 on 2024-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0004_auto_20240219_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
