# Generated by Django 5.0.2 on 2024-03-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0005_alter_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='track',
            field=models.CharField(max_length=20),
        ),
    ]
